### ISSUE TITLE
Illegal inheritance

### ISSUE THREAD

**Issue by tbeu** [ORNL-Modelica/Modelica-GNU_ScientificLibrary#1]
I believe if it is not legal that GNU_ScientificLibrary.Icons extends from GNU_ScientificLibrary.Icons.IconsPackage. See how it is done in the MSL, where the inheritance is missing but the graphics annotation is repeated.

**Comment by greenwoodms06** [comment]
I think I understand what your saying but are you getting some sort of warning...? I haven't had any issues with the current implementation...

**Comment by tbeu** [comment]
Yes, I see this syntax error
```
Error: attempted redefinition of IconsPackage was ignored
File: C:/Projekte/Modelica-GNU_ScientificLibrary/GNU_ScientificLibrary/Icons/IconsPackage/package.mo, line 2
Using old definition from:
File: C:/Projekte/Modelica-GNU_ScientificLibrary/GNU_ScientificLibrary/Icons/package.mo, line 3
```

**Comment by greenwoodms06** [comment]
Are you using OMEdit, Dymola, jModelica, other...?

I went ahead and opened in OMEdit and noticed the load error of the icons package. I fixed it my last commit... Did that fix the issue you were mentioning?

**Comment by greenwoodms06** [comment]
I will close this issue if I have addressed what you were mentioning.
