### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by tbeu** [ORNL-Modelica/Modelica-GNU_ScientificLibrary#2]
I believe it is not legal to license Modelica-GNU_ScientificLibrary under Modelica License 2. On https://www.gnu.org/software/gsl/ it says:
If I wanted to distribute an application which uses GSL, what license would I need to use?
The GNU General Public License (GPL).

**Comment by greenwoodms06** [comment]
I think that sounds reasonable after reading that. I switched the license. Thanks for pointing that out.

**Comment by dietmarw** [comment]
You should probably also fix this in the README

**Comment by tbeu** [comment]
I am not a lawyer but licensing it both under Modelica License 2 and GPL does not seem correct to me, as both licenses are not compatible and it also violates the GSL permission as stated above.
