### ISSUE TITLE
LICENSE.md file

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/Modelica-GNU_ScientificLibrary#4]
You might want to add a License file in addition to mentioning it in the Readme.
The most convenient way is to do it using the github webinterface:
Click `Create new file` and as name enter `LICENSE.md`.
A dropdown menu will appear where you can choose GPL.
Are you using GPL v2 or v3?
http://choosealicense.com/licenses/

**Comment by thorade** [comment]
Another special file you might want to add is `CONTRIBUTING.md`
https://github.com/blog/1184-contributing-guidelines

**Comment by greenwoodms06** [comment]
Thanks for the suggestions. I went ahead and added the license.md .
The contribution guide in some way will be generated in the future.
